In [1]:
# import numpy
import numpy

In [3]:
array = [[ 1., 0., 0.],
 [ 0., 1., 2.]]

In [6]:

nparray = numpy.array(array)
print type(array)
print type(nparray)

<type 'list'>
<type 'numpy.ndarray'>


In [7]:
print array

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]


In [8]:
print nparray

[[ 1.  0.  0.]
 [ 0.  1.  2.]]


In [10]:
# number of dimensions
nparray.ndim

2

In [1]:
# read in the data
# we will go over these blocks of code
# in a few weeks
raw_housing_prices = open('housing-prices.txt','r').readlines()

# extract column names and create
# a list of lists for the data
# and a dictionary of lists for the data
header = raw_housing_prices[0].split('\t')
housing_prices_list = []
housing_prices_dict = {}
for line in raw_housing_prices[1:]:
    datum = [float(a) for a in line.split('\t')]
    housing_prices_list.append(datum)
    for i,a in enumerate(header):
        if a not in housing_prices_dict:
            housing_prices_dict[a] = []
        housing_prices_dict[a].append(datum[i])

In [5]:
import numpy
housing_prices_np = numpy.array(housing_prices_list)
print housing_prices_np
print housing_prices_list[-3:]

[[  1.42212000e+05   1.98200000e+03   3.00000000e+00   1.00000000e+00
    0.00000000e+00   1.33000000e+02]
 [  1.34865000e+05   1.67600000e+03   3.00000000e+00   1.50000000e+00
    1.00000000e+00   1.40000000e+01]
 [  1.18007000e+05   1.69400000e+03   3.00000000e+00   2.00000000e+00
    1.00000000e+00   1.50000000e+01]
 ..., 
 [  1.54829000e+05   1.44000000e+03   2.00000000e+00   2.00000000e+00
    1.00000000e+00   6.60000000e+01]
 [  1.79492000e+05   2.03000000e+03   3.00000000e+00   2.50000000e+00
    1.00000000e+00   3.00000000e+00]
 [  1.89108000e+05   2.09700000e+03   3.00000000e+00   2.50000000e+00
    1.00000000e+00   1.00000000e+01]]
[[154829.0, 1440.0, 2.0, 2.0, 1.0, 66.0], [179492.0, 2030.0, 3.0, 2.5, 1.0, 3.0], [189108.0, 2097.0, 3.0, 2.5, 1.0, 10.0]]


In [14]:
housing_prices_np.shape

(1057, 6)

In [19]:
# compute the mean of the columns
# note axis = 0 is column means
# and axis = 1 is row means
means = numpy.mean(housing_prices_np, axis=0) 
print "housing prices mean:", means[0]

housing prices mean: 167901.857143


In [21]:
# compute the std of the columns
# note axis = 0 is column std
# and axis = 1 is row std
stds = numpy.std(housing_prices_np, axis=0) 
print "housing prices std:", stds[0]

 housing prices std: 77121.8392551


In [24]:
import numpy as np
# compute the median of the columns
# note axis = 0 is column median
# and axis = 1 is row median
np.percentile(housing_prices_np, 50, axis=0)

array([  1.52404000e+05,   1.67500000e+03,   3.00000000e+00,
         2.00000000e+00,   1.00000000e+00,   1.80000000e+01])

In [26]:
# build boxplot values
# compute the median of the columns
# note axis = 0 is column median
# and axis = 1 is row median
medians = np.percentile(housing_prices_np, 50, axis=0)
p25 = np.percentile(housing_prices_np, 25, axis=0)
p75 = np.percentile(housing_prices_np, 75, axis=0)

for i,h in enumerate(header):
    print h, p25[i], medians[i], p75[i]

 Price 112400.0 152404.0 206512.0
Living.Area 1342.0 1675.0 2223.0
Bedrooms 3.0 3.0 4.0
Bathrooms 1.5 2.0 2.5
Fireplaces 0.0 1.0 1.0
Age
6.0 18.0 34.0
